[package]
name = "libadb-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }
arbitrary = { version = "1", features = ["derive"] }
bytes = "1"

[dependencies.libadb]
path = "../libadb"

[[bin]]
name = "packet_decode"
path = "fuzz_targets/packet_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "shell_v2_frames"
path = "fuzz_targets/shell_v2_frames.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sync_parse"
path = "fuzz_targets/sync_parse.rs"
test = false
doc = false
bench = false

[profile.release]
debug = 1
